name: Deploy to GKE

on:
  push:
    branches: [ "main" ]  # change to "master" or your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: aesthetic-fiber-455210-g0

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/aesthetic-fiber-455210-g0/microservice-app .
          docker push gcr.io/aesthetic-fiber-455210-g0/microservice-app

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials springboot-cluster \
            --zone us-central1-c \
            --project aesthetic-fiber-455210-g0

      - name: Deploy to GKE
        run: kubectl apply -f k8s/app-deployment.yaml